version: '3.8'

services:
  backend-node:
    build: ./backend
    restart: always
    ports:
      - "5000:5000" 
    networks:
      - mern_network
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  
    networks:
      - mern_network


  mongodb:
    image: mongo:latest  
    ports:
      - "27018:27017"  
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db  

networks:
  mern_network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local