name: CI/CD Pipeline with Docker Compose and Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backendNode image
        run: |
          docker build -t shivam05gupta/backend-node ./backend
          docker push shivam05gupta/backend-node

      - name: Build and push frontend image
        run: |
          docker build -t shivam05gupta/mern-frontend ./frontend
          docker push shivam05gupta/mern-frontend

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Compose up
        run: docker-compose up -d --build

      - name: Wait for services to be ready
        run: sleep 10

      # - name: Tear down
      #   run: docker-compose down
